sudo: required
dist: trusty
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_script:
  - ./scripts/start-kc-server.sh
  - ./scripts/start-server.sh
script:
   - make ci
after_script:
  - ./scripts/stop-kc-server.sh
  - ./scripts/stop-server.sh
notifications:
  irc: "irc.freenode.org#brass-monkey"
branches:
  only:
    - master
